include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
linter:
  rules:
    avoid_print: false
    prefer_const_constructors: false
    use_key_in_widget_constructors: false
