// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXnB0ZCtRjxTdLwHPE3-9IeZj1HqBBbRk',
    appId: '1:1059717391242:web:cc8a0ff818a944798a1e73',
    messagingSenderId: '1059717391242',
    projectId: 'pathpulse-5d2f3',
    authDomain: 'pathpulse-5d2f3.firebaseapp.com',
    storageBucket: 'pathpulse-5d2f3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuKo_55VfnNWTaKFGrGfMPaGxfQgI9zhU',
    appId: '1:1059717391242:android:9ce2671fcc779cc38a1e73',
    messagingSenderId: '1059717391242',
    projectId: 'pathpulse-5d2f3',
    storageBucket: 'pathpulse-5d2f3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFroDO_mvULahip5_w-IKnaldfkYqmJPU',
    appId: '1:1059717391242:ios:1262c648a730e0268a1e73',
    messagingSenderId: '1059717391242',
    projectId: 'pathpulse-5d2f3',
    storageBucket: 'pathpulse-5d2f3.firebasestorage.app',
    iosBundleId: 'com.example.tacticalDisasterSimulation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFroDO_mvULahip5_w-IKnaldfkYqmJPU',
    appId: '1:1059717391242:ios:1262c648a730e0268a1e73',
    messagingSenderId: '1059717391242',
    projectId: 'pathpulse-5d2f3',
    storageBucket: 'pathpulse-5d2f3.firebasestorage.app',
    iosBundleId: 'com.example.tacticalDisasterSimulation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXnB0ZCtRjxTdLwHPE3-9IeZj1HqBBbRk',
    appId: '1:1059717391242:web:11bf89563917a9d28a1e73',
    messagingSenderId: '1059717391242',
    projectId: 'pathpulse-5d2f3',
    authDomain: 'pathpulse-5d2f3.firebaseapp.com',
    storageBucket: 'pathpulse-5d2f3.firebasestorage.app',
  );
}
